# Generated by Django 2.0 on 2018-12-20 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='production_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 16, 46, 23, 718164, tzinfo=utc)),
        ),
    ]
